query projectMembers($projectId: Int!) {
  projectMembers(projectId: $projectId) {
    id
    project {
      id
    }
    givenName
    surName
    orcid
    email
    affiliation {
      uri
      name
    }
    isPrimaryContact
    memberRoles {
      id
      uri
    }
    created
    createdById
    modified
    modifiedById
  }
}

query planMembers($planId: Int!) {
  planMembers(planId: $planId) {
    id
    plan {
      id
    }
    projectMember {
      id
    }
    isPrimaryContact
    memberRoles {
      id
      uri
    }
    created
    createdById
    modified
    modifiedById
  }
}

query MemberRoles {
  memberRoles {
    id
    uri
    label
    description
    isDefault
  }
}
