query Plans($projectId: Int!) {
  plansByProjectId(projectId: $projectId) {
    id
    title
  }
}

query PlanByDmpId($dmpId: String!) {
  planByDMPId(dmpId: $dmpId) {
    id
    dmpId
    title
    visibility
    status
    created
    createdById
    modified
    modifiedById
    registered
    project {
      id
      title
      abstractText
      startDate
      endDate
      isTestProject
      researchDomain {
        id
        uri
      }
      members {
        id
        isPrimaryContact
        affiliation {
          uri
        }
        givenName
        surName
        orcid
        email
        memberRoles {
          id
          uri
        }
      }
      fundings {
        id
        affiliation {
          uri
        }
        status
        funderProjectNumber
        funderOpportunityNumber
        grantId
      }
    }
    members {
      projectMember {
        id
      }
      memberRoles {
        id
        uri
      }
    }
    fundings {
      id
      projectFunding {
        id
      }
    }
    answers {
      id
      versionedSection{
        id
      }
      versionedQuestion {
        id
      }
      json
    }
    versionedTemplate {
      id
      name
      description
      version
      template {
        id
      }
      versionedSections {
        id
        name
        displayOrder
        versionedQuestions {
          id
          questionText
          json
        }
      }
    }
    alternateIdentifiers {
      id
      alternateIdentifier
    }
  }
}

query PlanByAlternateIdentifier($alternateIdentifier: String!) {
  planByAlternateIdentifier(alternateIdentifier: $alternateIdentifier) {
    id
    dmpId
    title
    visibility
    status
    created
    createdById
    modified
    modifiedById
    registered
    project {
      id
      title
      abstractText
      startDate
      endDate
      isTestProject
      researchDomain {
        id
        uri
      }
      members {
        id
        isPrimaryContact
        affiliation {
          uri
        }
        givenName
        surName
        orcid
        email
        memberRoles {
          id
          uri
        }
      }
      fundings {
        id
        affiliation {
          uri
        }
        status
        funderProjectNumber
        funderOpportunityNumber
        grantId
      }
    }
    members {
      projectMember {
        id
      }
      memberRoles {
        id
        uri
      }
    }
    fundings {
      id
      projectFunding {
        id
      }
    }
    answers {
      id
      versionedSection{
        id
      }
      versionedQuestion {
        id
      }
      json
    }
    versionedTemplate {
      id
      name
      description
      version
      template {
        id
      }
      versionedSections {
        id
        name
        displayOrder
        versionedQuestions {
          id
          questionText
          json
        }
      }
    }
    alternateIdentifiers {
      id
      alternateIdentifier
    }
  }
}
