FROM public.ecr.aws/amazonlinux/amazonlinux:2023 AS builder

RUN dnf upgrade -y
RUN dnf -y install nodejs22

WORKDIR /app

# Install all deps
COPY package*.json ./
RUN npm ci --omit=dev

# Expose API port
EXPOSE 4060

CMD ["node", "dist/server.js"]
