mutation AddAnswer($planId: Int!, $versionedSectionId: Int, $versionedQuestionId: Int, $versionedCustomSectionId: Int, $versionedCustomQuestionId: Int, $json: String) {
  addAnswer(planId: $planId, versionedSectionId: $versionedSectionId, versionedQuestionId: $versionedQuestionId, versionedCustomSectionId: $versionedCustomSectionId, versionedCustomQuestionId: $versionedCustomQuestionId, json: $json) {
    id
    json
    errors {
      json
      planId
      versionedSectionId
      versionedQuestionId
    }
  }
}

mutation UpdateAnswer($answerId: Int!, $json: String) {
  updateAnswer(answerId: $answerId, json: $json) {
    id
    json
    errors {
      json
    }
  }
}
