mutation AddProjectCollaborator($projectId: Int!, $email: String!) {
  addProjectCollaborator(projectId: $projectId, email: $email) {
    id
    email
    accessLevel
    user {
      id
      email
    }
    invitedBy {
      id
      email
    }
    created
    createdById
    modified
    modifiedById
    errors {
      general
      email
      accessLevel
    }
  }
}

mutation UpdateProjectCollaborator($projectCollaboratorId: Int!, $accessLevel: ProjectCollaboratorAccessLevel!) {
  updateProjectCollaborator(projectCollaboratorId: $projectCollaboratorId, accessLevel: $accessLevel) {
    errors {
      general
      accessLevel
    }
    id
    modified
    modifiedById
    accessLevel
  }
}

mutation RemoveProjectCollaborator($projectCollaboratorId: Int!) {
  removeProjectCollaborator(projectCollaboratorId: $projectCollaboratorId) {
    id
    modified
    modifiedById
    errors {
      general
    }
  }
}
