mutation AddProjectFunding($input: AddProjectFundingInput!) {
  addProjectFunding(input: $input) {
    id
    status
    funderOpportunityNumber
    funderProjectNumber
    grantId
    affiliation {
      uri
      name
    }
    errors {
      general
      projectId
      affiliationId
      status
      funderProjectNumber
      grantId
      funderOpportunityNumber
    }
  }
}

mutation UpdateProjectFunding($input: UpdateProjectFundingInput!) {
  updateProjectFunding(input: $input) {
    id
    status
    funderOpportunityNumber
    funderProjectNumber
    grantId
    affiliation {
      uri
      name
    }
    errors {
      general
      projectId
      affiliationId
      status
      funderProjectNumber
      grantId
      funderOpportunityNumber
    }
  }
}

mutation RemoveProjectFunding($projectFundingId: Int!) {
  removeProjectFunding(projectFundingId: $projectFundingId) {
    id
    errors {
      general
      projectId
      affiliationId
      status
      funderProjectNumber
      grantId
      funderOpportunityNumber
    }
  }
}

mutation AddPlanFunding($planId: Int!, $projectFundingIds: [Int!]!) {
  addPlanFunding(planId: $planId, projectFundingIds: $projectFundingIds) {
    id
    fundings {
      id
      projectFunding {
        id
      }
    }
    errors {
      general
    }
  }
}

mutation UpdatePlanFunding($planId: Int!, $projectFundingIds: [Int!]!) {
  updatePlanFunding(planId: $planId, projectFundingIds: $projectFundingIds) {
    id
    projectFunding {
      id
    }
    errors {
      general
      planId
      ProjectFundingId
    }
  }
}

mutation RemovePlanFunding($planFundingId: Int!) {
  removePlanFunding(planFundingId: $planFundingId) {
    id
    projectFunding {
      id
    }
    errors {
      general
      planId
      ProjectFundingId
    }
  }
}

