mutation AddPlan($projectId: Int!, $versionedTemplateId: Int!) {
  addPlan(projectId: $projectId, versionedTemplateId: $versionedTemplateId) {
    id
    created
    createdById
    modified
    modifiedById
    dmpId
    errors {
      general
      versionedTemplateId
      projectId
    }
  }
}

mutation UpdatePlan($input: UpdatePlanInput!) {
  updatePlan(input: $input) {
    errors {
      general
      title
      status
      visibility
      languageId
    }
    id
    dmpId
    modified
    modifiedById
    title
    status
    visibility
    languageId
  }
}

mutation ArchivePlan($planId: Int!) {
  archivePlan(planId: $planId) {
    id
    modified
    modifiedById
    errors {
      general
    }
  }
}

mutation AddAlternateIdentifier($planId: Int!, $alternateIdentifier: String!) {
  addAlternateIdentifierToPlan(planId: $planId, alternateIdentifier: $alternateIdentifier) {
    errors {
      general
      alternateIdentifier
      planId
    }
    id
    alternateIdentifier
    plan {
      id
    }
  }
}

mutation RemoveAlternateIdentifier($planId: Int!, $alternateIdentifier: String!) {
  removeAlternateIdentifierFromPlan(planId: $planId, alternateIdentifier: $alternateIdentifier) {
    errors {
      general
      alternateIdentifier
      planId
    }
    id
    alternateIdentifier
    plan {
      id
    }
  }
}
