mutation AddProject($title: String!, $isTestProject: Boolean) {
  addProject(title: $title, isTestProject: $isTestProject) {
    id
    created
    createdById
    modified
    modifiedById
    errors {
      title
      general
    }
  }
}

mutation UpdateProject($input: UpdateProjectInput!) {
  updateProject(input: $input) {
    id
    created
    createdById
    modified
    modifiedById
    title
    abstractText
    startDate
    endDate
    researchDomainId
    isTestProject
    errors {
      general
      title
      abstractText
      endDate
      startDate
      researchDomainId
      isTestProject
    }
  }
}

mutation ArchiveProject($projectId: Int!) {
  archiveProject(projectId: $projectId) {
    id
    modified
    modifiedById
    errors {
      general
    }
  }
}
